name: 'upyun-upx-action'
author: 'YaoKun <yaokun@bwcxtech.com>'
description: 'Deploy your files to upyun using upyun-upx.'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'blue'
  icon: 'upload-cloud'
